import { builtinModules } from "node:module";
import chokidar from "chokidar";
import esbuild from "esbuild";
import process from "process";
import { fileInliner } from "./build/file-inliner.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";
let cssChanged = false;

const stylesPlugin = {
	name: "styles",
	setup(build) {
		build.onEnd(async () => {
			try {
				if (fileInliner("src/Styles/styles.css", "styles.css")) cssChanged = true;
				if (cssChanged) console.log("[styles] generated styles.css");
			} catch (error) {
				console.error("[styles] Error:", error);
				process.exit(1);
			}

			await esbuild
				.build({
					entryPoints: ["styles.css"],
					bundle: false,
					write: false,
				})
				.catch((error) => {
					console.error("[styles] Error:", error);
					process.exit(1);
				});
		});
	},
};

const buildStart = {
	name: "build-start",
	setup(build) {
		build.onStart(() => {
			cssChanged = false;
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron", ...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	plugins: [buildStart, stylesPlugin],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
}

await context.watch();

const watcher = chokidar.watch(["src/main.ts", "src/Styles"]);
watcher.on("ready", () => {
	console.log("[watch] watching for changes...");
});
watcher.on("change", async (path) => {
	console.log(`[watch] file modified: ${path}`);
	try {
		await context.rebuild();
	} catch (error) {
		console.error("[watch] rebuild failed:", error);
	}
});
